plugins {
    id 'com.android.application'
}

android {
    namespace "cn.classboard.inbox"
    compileSdk 36

    defaultConfig {
        applicationId "cn.classboard.inbox"
        minSdk 23
        targetSdk 36
        versionCode 9
        versionName "2.2.0"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
    }
}
