import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { readFile,readdir } from 'node:fs/promises';
import { randomBytes,randomUUID,pbkdf2Sync } from 'node:crypto';
import assert from 'node:assert/strict';
const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:await readFile('dist/_worker.js','utf8'),compatibilityDate:'2026-09-09',d1Databases:['DB']}));
try{
  const db=await mf.getD1Database('DB');
  for(const file of (await readdir('migrations')).sort())for(const statement of (await readFile('migrations/'+file,'utf8')).split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();
  const secret=randomBytes(24).toString('hex'),salt=randomBytes(16).toString('hex');
  await db.prepare("INSERT INTO users(id,student_id,display_name,role,salt,digest,created_at,must_change_password) VALUES(?,?,?,'committee',?,?,?,0)").bind(randomUUID(),'integration-admin','测试班委',salt,pbkdf2Sync(secret,salt,100000,32,'sha256').toString('hex'),new Date().toISOString()).run();
  let cookie='';
  const call=(path,method='GET',body,auth=true,origin='https://example.test')=>mf.dispatchFetch('https://example.test/api'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,...(auth&&cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
  assert.equal((await call('/admin/notices')).status,401);
  assert.equal((await call('/login','POST',{student_id:'integration-admin',name:'测试班委',password:secret},false,'https://evil.test')).status,403);
  const login=await call('/login','POST',{student_id:'integration-admin',name:'测试班委',password:secret});assert.equal(login.status,200);
  const setCookie=login.headers.get('Set-Cookie');assert.match(setCookie,/HttpOnly/);assert.match(setCookie,/Secure/);assert.match(setCookie,/SameSite=Strict/);cookie=setCookie.split(';')[0];
  assert.equal((await call('/notices','GET',undefined,false)).status,401);
  assert.equal((await call('/login','POST',{student_id:'integration-admin',name:'错误姓名',password:secret})).status,401);
  const committeeCookie=cookie;
  const studentId=randomUUID();
  await db.prepare("INSERT INTO users(id,student_id,display_name,role,salt,digest,created_at) VALUES(?,?,?,'student',?,?,?)").bind(studentId,'test-student','测试同学',salt,pbkdf2Sync(secret,salt,100000,32,'sha256').toString('hex'),new Date().toISOString()).run();
  const studentLogin=await call('/login','POST',{student_id:'test-student',name:'测试同学',password:secret});
  cookie=studentLogin.headers.get('Set-Cookie').split(';')[0];
  assert.equal((await call('/notices')).status,403);
  assert.equal((await call('/admin/notices')).status,403);
  assert.equal((await call('/account/reads')).status,403);
  assert.equal((await call('/account/password','POST',{current_password:secret,new_password:'short'})).status,400);
  const newSecret=randomBytes(24).toString('hex');
  assert.equal((await call('/account/password','POST',{current_password:secret,new_password:newSecret})).status,200);
  assert.equal((await call('/notices')).status,401);
  assert.equal((await call('/login','POST',{student_id:'test-student',name:'测试同学',password:secret})).status,401);
  const studentAgain=await call('/login','POST',{student_id:'test-student',name:'测试同学',password:newSecret});
  assert.equal(studentAgain.status,200);
  const studentCookie=studentAgain.headers.get('Set-Cookie').split(';')[0];cookie=studentCookie;
  assert.equal((await call('/admin/notices')).status,403);
  assert.equal((await call('/admin/import','POST',{})).status,403);
  cookie=committeeCookie;
  const notice={title:'集成测试通知',body:'请在明天完成作业',category:'作业',location:'教三201',audience:'全体',event_at:null,deadline_at:'2026-09-12T12:00:00Z',pinned:false};
  const create=await call('/admin/notices','POST',notice);assert.equal(create.status,201);const {id}=await create.json();
  let list=await(await call('/notices')).json();assert.equal(list.notices.length,1);assert.equal(list.notices[0].source_text,undefined);
  assert.equal((await call('/admin/notices/'+id,'PUT',{...notice,pinned:true,version:1})).status,200);
  assert.equal((await call('/admin/notices/'+id,'PUT',{...notice,version:1})).status,409);
  list=await(await call('/notices?category=活动')).json();assert.equal(list.notices.length,0);
  await db.prepare("UPDATE notices SET status='pending',source_text='PRIVATE SOURCE' WHERE id=?").bind(id).run();
  assert.equal((await(await call('/notices')).json()).notices.length,0);
  assert.equal((await call('/notices/'+id)).status,404);
  assert.equal((await call('/admin/notices/'+id+'/publish','POST',{version:2},false)).status,401);
  assert.equal((await call('/admin/notices/'+id+'/publish','POST',{version:2})).status,200);
  assert.equal((await call('/admin/notices/'+id+'/publish','POST',{version:2})).status,409);
  list=await(await call('/notices')).json();assert.equal(list.notices.length,1);assert.equal(list.notices[0].source_text,undefined);assert.equal(list.notices[0].pinned,true);
  assert.equal((await call('/admin/notices/'+id+'/archive','POST',{version:3})).status,200);
  assert.equal((await(await call('/notices')).json()).notices.length,0);
  const parse=await call('/admin/parse','POST',{text:'@全体成员 高数作业明晚8点前提交。',referenceDate:'2026-09-09T10:00:00+08:00'});assert.equal(parse.status,200);
  const parsed=await parse.json();assert.equal(parsed.drafts.length,1);assert.equal(parsed.drafts[0].deadline_at,'2026-09-10T12:00:00.000Z');
  const imported=await call('/admin/import','POST',{drafts:parsed.drafts,source:'text',status:'published'});assert.equal(imported.status,201);assert.equal((await imported.json()).imported,1);
  assert.equal((await(await call('/notices')).json()).notices.length,0);
  const dup=await call('/admin/import','POST',{drafts:parsed.drafts,source:'text'});assert.equal((await dup.json()).skipped,1);
  const all=await(await call('/admin/notices')).json();const pending=all.notices.find(n=>n.status==='pending');assert.ok(pending);assert.ok(pending.source_text);
  cookie=studentCookie;
  assert.equal((await call('/notices/'+pending.id)).status,404);
  assert.equal((await call('/account/reads/'+pending.id,'PUT')).status,404);
  assert.equal((await call('/admin/notices/'+pending.id+'/publish','POST',{version:pending.version})).status,403);
  assert.equal((await(await call('/notices')).json()).notices.length,0);
  cookie=committeeCookie;
  assert.equal((await call('/admin/notices/'+pending.id+'/publish','POST',{version:pending.version})).status,200);
  assert.equal((await(await call('/notices')).json()).notices.length,1);
  cookie=studentCookie;
  assert.equal((await call('/account/reads/'+pending.id,'PUT')).status,200);
  assert.deepEqual((await(await call('/account/reads')).json()).ids,[pending.id]);
  cookie=committeeCookie;
  assert.deepEqual((await(await call('/account/reads')).json()).ids,[]);
  cookie=studentCookie;
  const otherDevice=await call('/login','POST',{student_id:'test-student',name:'测试同学',password:newSecret});
  cookie=otherDevice.headers.get('Set-Cookie').split(';')[0];
  assert.deepEqual((await(await call('/account/reads')).json()).ids,[pending.id]);
  assert.equal((await call('/account/reads/'+pending.id,'DELETE')).status,200);
  cookie=studentCookie;
  const studentView=await(await call('/notices')).json();assert.equal(studentView.notices[0].source_text,undefined);assert.equal(studentView.notices[0].warnings,undefined);
  assert.deepEqual((await(await call('/account/reads')).json()).ids,[]);
  assert.equal((await call('/account/password','POST',{current_password:newSecret,new_password:newSecret})).status,400);
  assert.equal((await call('/account/password','POST',{current_password:'wrong',new_password:randomBytes(24).toString('hex')})).status,400);
  assert.equal((await call('/account/password','POST',{current_password:newSecret,new_password:randomBytes(24).toString('hex')})).status,200);
  assert.equal((await call('/notices')).status,401);
  cookie=otherDevice.headers.get('Set-Cookie').split(';')[0];assert.equal((await call('/notices')).status,401);
  cookie=committeeCookie;
  assert.equal((await call('/logout','POST',{})).status,200);assert.equal((await call('/admin/notices')).status,401);
  assert.equal((await call('/admin/parse','POST',{text:'作业明天交',referenceDate:'2026-09-09T10:00:00+08:00'})).status,401);
  for(let i=0;i<8;i++)assert.equal((await call('/login','POST',{student_id:'unknown',name:'未知',password:secret})).status,401);
  assert.equal((await call('/login','POST',{student_id:'unknown',name:'未知',password:secret})).status,429);
  console.log('PASS: 姓名学号登录、首次改密、旧密码失效、全部会话撤销、限流、同学权限、个人已读隔离与跨设备同步、发布筛选置顶、并发编辑、待审隔离、解析导入审核归档。');
}finally{await mf.dispose();}
