import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { Bell, LayoutDashboard, CalendarDays, Inbox, Settings2, ArrowUpRight, ArrowRight, Search, Plus, Pin, Clock3, MapPin, BookOpen, PartyPopper, ClipboardList, GraduationCap, Check, ChevronRight, LogIn, LogOut, Menu, Users, FileText, Archive, Pencil, RefreshCw, CalendarCheck2, X, CheckCheck } from 'lucide-react';
import { api } from './api';
import { categories,emptyNotice,type Admin,type Category,type Notice,type NoticeInput } from './shared/types';
import { countdown,dayKey,effectiveEnd,formatDate,isExpired } from './shared/dates';
import { Modal } from './components/Modal';
import { NoticeForm } from './components/NoticeForm';

type Page='today'|'notices'|'schedule'|'manage';
const icons={作业:BookOpen,活动:PartyPopper,事务:ClipboardList,课程:GraduationCap};
const catClass={作业:'homework',活动:'activity',事务:'affair',课程:'course'};
const statusNames={pending:'待审核',published:'已发布',rejected:'已驳回',archived:'已归档'};
function loadRead():string[]{try{return JSON.parse(localStorage.getItem('classboard-read')||'[]');}catch{return [];}}

export default function App(){
  const [page,setPage]=useState<Page>('today'),[admin,setAdmin]=useState<Admin|null>(null),[notices,setNotices]=useState<Notice[]>([]),[managed,setManaged]=useState<Notice[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[login,setLogin]=useState(false),[edit,setEdit]=useState<Notice|NoticeInput|null>(null),[detail,setDetail]=useState<Notice|null>(null),[confirm,setConfirm]=useState<{n:Notice;action:string}|null>(null);
  const [category,setCategory]=useState('全部'),[query,setQuery]=useState(''),[period,setPeriod]=useState('active'),[read,setRead]=useState<string[]>(loadRead),[manageFilter,setManageFilter]=useState('published'),[menu,setMenu]=useState(false),[now,setNow]=useState(Date.now()),[actionBusy,setActionBusy]=useState(false);
  const refresh=async()=>{setError('');try{const r=await api<{notices:Notice[]}>('/notices');setNotices(r.notices);if(admin){const m=await api<{notices:Notice[]}>('/admin/notices');setManaged(m.notices);}}catch(e){setError((e as Error).message);}finally{setLoading(false);}};
  useEffect(()=>{api<{admin:Admin|null}>('/session').then(r=>setAdmin(r.admin)).catch(()=>{});},[]);
  useEffect(()=>{void refresh();},[admin]);
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t);},[toast]);
  const go=(p:Page)=>{setPage(p);setMenu(false);setQuery('');setCategory('全部');};
  const markRead=(id:string)=>{const updated=read.includes(id)?read.filter(x=>x!==id):[...read,id];setRead(updated);try{localStorage.setItem('classboard-read',JSON.stringify(updated.slice(-2000)));}catch{setToast('浏览器未允许保存已读状态');}};
  const open=(n:Notice)=>{setDetail(n);if(!read.includes(n.id)){const updated=[...read,n.id];setRead(updated);try{localStorage.setItem('classboard-read',JSON.stringify(updated.slice(-2000)));}catch{}}};
  const active=notices.filter(n=>!isExpired(n,now));
  const today=dayKey(new Date(now));
  const todayNotices=notices.filter(n=>dayKey(n.published_at||n.created_at)===today||n.event_at&&dayKey(n.event_at)===today||n.deadline_at&&dayKey(n.deadline_at)===today);
  const upcoming=useMemo(()=>notices.flatMap(n=>[
    ...(n.event_at?[{n,date:n.event_at,label:'活动时间'}]:[]),
    ...(n.deadline_at&&n.deadline_at!==n.event_at?[{n,date:n.deadline_at,label:'截止时间'}]:[])
  ]).filter(x=>Date.parse(x.date)>=now&&Date.parse(x.date)<now+7*86400000).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date)),[notices,now]);
  const shown=useMemo(()=>{
    const base=page==='manage'?managed.filter(n=>n.status===manageFilter):page==='today'?todayNotices:notices;
    return base.filter(n=>(category==='全部'||n.category===category)&&(!query||`${n.title} ${n.body} ${n.location}`.toLowerCase().includes(query.toLowerCase()))&&(page!=='notices'||period==='all'||(period==='active'?!isExpired(n,now):period==='expired'?isExpired(n,now):period==='unread'?!read.includes(n.id):!!effectiveEnd(n)&&Date.parse(effectiveEnd(n)!)>=now&&Date.parse(effectiveEnd(n)!)<now+7*86400000)));
  },[page,managed,manageFilter,notices,category,query,period,read,now]);
  const save=async(n:NoticeInput)=>{const existing=edit&&'id'in edit?edit:null;await api(existing?`/admin/notices/${existing.id}`:'/admin/notices',{method:existing?'PUT':'POST',body:JSON.stringify({...n,...(existing?{version:existing.version}:{})})});setEdit(null);setToast(existing?'通知已更新':'通知已发布');await refresh();};
  const pin=async(n:Notice)=>{try{await api(`/admin/notices/${n.id}`,{method:'PUT',body:JSON.stringify({...n,pinned:!n.pinned})});setToast(n.pinned?'已取消置顶':'已置顶');await refresh();}catch(e){setToast((e as Error).message);}};
  const doAction=async()=>{if(!confirm)return;setActionBusy(true);try{await api(`/admin/notices/${confirm.n.id}/${confirm.action}`,{method:'POST',body:JSON.stringify({version:confirm.n.version})});setConfirm(null);setDetail(null);setToast('操作成功');await refresh();}catch(e){setToast((e as Error).message);}finally{setActionBusy(false);}};
  const logout=async()=>{try{await api('/logout',{method:'POST',body:'{}'});setAdmin(null);setManaged([]);setDetail(null);setEdit(null);go('today');setToast('已退出班委账号');}catch(e){setToast((e as Error).message);}};
  const nav=[{id:'today' as Page,label:'今日看板',icon:LayoutDashboard},{id:'notices' as Page,label:'全部通知',icon:Bell},{id:'schedule' as Page,label:'近期日程',icon:CalendarDays}];
  const card=(n:Notice)=>{const Icon=icons[n.category];const expired=isExpired(n,now);return <article key={n.id} className={`notice-card ${n.pinned?'is-pinned':''} ${expired?'is-expired':''}`}>
    <div className={`notice-symbol ${catClass[n.category]}`}><Icon size={22}/></div><div className="notice-main"><div className="notice-meta"><span className={`category-badge ${catClass[n.category]}`}>{n.category}</span>{n.pinned&&<span className="pin-label"><Pin size={12}/>置顶</span>}{page==='manage'&&<span className="muted">{statusNames[n.status]}</span>}<span className="notice-time">{formatDate(n.published_at||n.created_at)} 发布</span></div>
      <button className="notice-title" onClick={()=>open(n)}>{n.title}</button><p className="notice-preview">{n.body}</p>
      <div className="notice-foot"><div className="notice-facts">{effectiveEnd(n)&&<span className={expired?'expired-text':''}><Clock3 size={14}/>{formatDate(effectiveEnd(n))}{n.deadline_at?' 截止':''}</span>}{n.location&&<span><MapPin size={14}/>{n.location}</span>}</div><button className={`read-button ${read.includes(n.id)?'read':''}`} onClick={()=>markRead(n.id)} aria-label={`${read.includes(n.id)?'标为未读':'标为已读'}：${n.title}`}>{read.includes(n.id)?<CheckCheck size={15}/>:<span className="unread-dot"/>}{read.includes(n.id)?'已读':'未读'}</button></div>
      {page==='manage'&&<div className="management-actions">{['published','pending'].includes(n.status)&&<><button onClick={()=>setEdit(n)}><Pencil size={14}/>编辑</button><button onClick={()=>void pin(n)}><Pin size={14}/>{n.pinned?'取消置顶':'置顶'}</button></>}{n.status==='published'&&<button onClick={()=>setConfirm({n,action:'archive'})}><Archive size={14}/>归档</button>}{n.status==='pending'&&<><button className="approve" onClick={()=>setConfirm({n,action:'publish'})}><Check size={14}/>审核发布</button><button onClick={()=>setConfirm({n,action:'reject'})}><X size={14}/>驳回</button></>}</div>}
    </div></article>;};
  return <div className="app-shell">
    <aside className={`sidebar ${menu?'open':''}`}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('today');}}><span className="brand-mark"><Bell size={23}/></span><span>知会<span className="brand-en">CLASSBOARD</span></span></a>
      <div className="class-switch"><span className="class-avatar">班</span><div><strong>我们的班级</strong><span>班级通知与日程</span></div><ChevronRight size={16}/></div>
      <p className="nav-label">班级空间</p><nav>{nav.map(({id,label,icon:Icon})=><button className={`nav-item ${page===id?'selected':''}`} key={id} onClick={()=>go(id)}><Icon size={20}/><span>{label}</span>{id==='notices'&&<span className="nav-count">{notices.length}</span>}</button>)}{admin&&<><p className="nav-label">班委工作台</p><button className={`nav-item ${page==='manage'?'selected':''}`} onClick={()=>go('manage')}><Settings2 size={20}/><span>通知管理</span></button></>}</nav>
      <div className="sidebar-bottom"><div className="side-note"><span className="note-line"/><p>重要的事，<br/>在这里看见。</p><span>少翻一次群，多一份从容。</span></div><button className="account" onClick={()=>admin?void logout():setLogin(true)}><span className="account-avatar">{admin?'委':'客'}</span><span><strong>{admin?.display_name||'游客浏览'}</strong><small>{admin?'班委账号 · 点击退出':'班委请登录管理'}</small></span>{admin?<LogOut size={17}/>:<LogIn size={17}/>}</button></div>
    </aside>
    {menu&&<button className="menu-scrim" aria-label="关闭导航" onClick={()=>setMenu(false)}/>}
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={()=>setMenu(!menu)}><Menu size={21}/></button><span>班级空间</span><ChevronRight size={14}/><strong>{page==='today'?'今日看板':page==='notices'?'全部通知':page==='schedule'?'近期日程':'通知管理'}</strong></div><div className="topbar-right"><span className="top-date">{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric',weekday:'long'}).format(now)}</span><span className="top-divider"/><span className="role-pill"><Users size={14}/>{admin?'班委':'同学视图'}</span></div></header>
    <main><div className="page-heading"><div><div className="eyebrow">{page==='today'?'YOUR CLASS, AT A GLANCE':page==='schedule'?'MAKE TIME FOR WHAT MATTERS':'KEEP EVERYONE IN THE LOOP'}</div><h1>{page==='today'?'今天，有什么新鲜事？':page==='notices'?'每一条通知，都在这里':page==='schedule'?'把日程安排得明明白白':'班委工作台'}<span className="heading-dot">.</span></h1><p>{page==='today'?'作业、活动与班级安排，一眼就知道。':page==='notices'?'按分类查找通知，不错过重要的截止时间。':page==='schedule'?'未来七天的活动与截止时间，提前一步准备。':'发布、编辑与整理班级通知。'}</p></div><div className="heading-actions">{admin?<button className="button primary" onClick={()=>setEdit(emptyNotice())}><Plus size={18}/>发布通知</button>:<button className="button secondary" onClick={()=>setLogin(true)}><LogIn size={17}/>班委登录</button>}</div></div>
    {error&&<div className="error error-banner" role="alert">{error}<button onClick={()=>void refresh()}><RefreshCw size={15}/>重试</button></div>}
    {page==='today'&&<><div className="overview-grid"><div className="welcome-panel"><div><span className="welcome-kicker"><span/>班级消息站</span><h2>消息不遗漏，<br/>安排心中有数。</h2><p>让通知有归处，让每一天更有条理。</p><button onClick={()=>go('notices')}>查看全部通知 <ArrowRight size={17}/></button></div><div className="board-art" aria-hidden="true"><div className="art-dot dot-one"/><div className="art-dot dot-two"/><div className="art-paper back"/><div className="art-paper front"><span className="art-clip"/><span className="art-paper-title">CLASS NOTES</span><div><span className="art-check"><Check size={16}/></span><i/></div><div><span className="art-check"><Check size={16}/></span><i/></div><div><span className="art-empty"/><i/></div><span className="art-stamp"><Bell size={26}/></span></div></div></div><div className="stat-panel"><div className="stat-icon blue"><Bell size={20}/></div><span>今日相关通知</span><strong>{todayNotices.length.toString().padStart(2,'0')}<small>条</small></strong><p>今日发布或需要处理</p></div><div className="stat-panel"><div className="stat-icon amber"><Clock3 size={20}/></div><span>七天内待办</span><strong>{new Set(upcoming.map(x=>x.n.id)).size.toString().padStart(2,'0')}<small>项</small></strong><p>{active.length} 条通知进行中</p></div></div></>}
    {page==='schedule'?<section className="schedule-page"><div className="section-heading"><h2><CalendarDays size={21}/>未来七天</h2><span>北京时间</span></div>{upcoming.length?Object.entries(Object.groupBy(upcoming,x=>dayKey(x.date))).map(([date,items])=><div key={date} className="schedule-day"><div className="schedule-date"><strong>{date.slice(8)}</strong><span>{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'short',weekday:'short'}).format(new Date(date+'T00:00:00+08:00'))}</span></div><div>{items?.map(x=><button className="schedule-event" key={x.n.id+x.label} onClick={()=>open(x.n)}><span>{formatDate(x.date).split(' ').at(-1)}</span><div><span className={`category-badge ${catClass[x.n.category]}`}>{x.n.category}</span><h3>{x.n.title}</h3><p>{x.label}{x.n.location?` · ${x.n.location}`:''}</p></div><ChevronRight size={18}/></button>)}</div></div>):<Empty title="未来七天暂无日程" text="有明确时间的通知发布后，会自动出现在这里。"/>}</section>:<div className={`content-grid ${page==='manage'?'full-width':''}`}><section className="notices-section"><div className="section-heading"><h2>{page==='today'?'今日通知':page==='manage'?'通知管理':'通知列表'}<span className="number-badge">{shown.length}</span></h2>{page==='today'?<button className="text-link" onClick={()=>go('notices')}>查看全部<ArrowUpRight size={16}/></button>:<button className="icon-button" aria-label="刷新通知" onClick={()=>void refresh()}><RefreshCw size={17}/></button>}</div>
      {page==='manage'&&<div className="manage-tabs">{Object.entries(statusNames).map(([s,label])=><button key={s} className={manageFilter===s?'active':''} onClick={()=>setManageFilter(s)}>{label}<span>{managed.filter(n=>n.status===s).length}</span></button>)}</div>}
      <div className="filters"><div className="category-tabs">{['全部',...categories].map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>{page==='notices'&&<select aria-label="按时间筛选" value={period} onChange={e=>setPeriod(e.target.value)}><option value="active">进行中</option><option value="all">全部时间</option><option value="week">七天内截止 / 开始</option><option value="expired">已过期</option><option value="unread">未读</option></select>}</div>
      {page!=='today'&&<label className="search"><Search size={17}/><input aria-label="搜索通知" placeholder="搜索标题、正文或地点…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={15}/></button>}</label>}
      <div className="notice-list">{loading?<div className="loading-state" role="status"><RefreshCw size={22} className="spin"/>正在获取班级通知…</div>:shown.length?shown.map(card):<Empty title={category!=='全部'||query?'没有找到匹配的通知':page==='today'?'今天暂时没有新通知':'这里还没有通知'} text={page==='today'?'可以看看全部通知，提前安排接下来的一周。':'调整筛选条件，或稍后再来看看。'}/>}</div>
      <div className="list-end"><span/> {shown.length?'已经看到这里的全部通知':'知会 · 班级消息站'} <span/></div>
    </section>{page!=='manage'&&<aside className="right-column"><section className="upcoming-panel"><div className="section-heading"><h2><CalendarDays size={18}/>近期日程</h2><button className="icon-button" aria-label="查看近期日程" onClick={()=>go('schedule')}><ArrowUpRight size={18}/></button></div><div className="week-strip">{Array.from({length:7},(_,i)=>{const d=new Date(now+i*86400000);return <div className={i===0?'current':''} key={i}><span>{new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',weekday:'narrow'}).format(d)}</span><strong>{dayKey(d).slice(8).replace(/^0/,'')}</strong><i className={upcoming.some(x=>dayKey(x.date)===dayKey(d))?'has-event':''}/></div>;})}</div><div className="timeline">{upcoming.length?upcoming.slice(0,4).map((x,i)=><button className="timeline-item" key={x.n.id+x.label} onClick={()=>open(x.n)}><span className={`timeline-point ${i===0?'first':''}`}/><span className="timeline-date">{formatDate(x.date)}</span><strong>{x.n.title}</strong><span className="timeline-place">{x.n.location||x.label}</span><span className={`countdown ${i===0?'soon':''}`}>{countdown(x.date,now)}</span></button>):<p className="small-empty">未来七天暂无待办，<br/>享受从容的一天。</p>}</div></section><section className="little-note"><span className="little-icon"><CalendarCheck2 size={20}/></span><h3>给忙碌的一点留白</h3><p>看完通知，标记已读。<br/>把注意力留给正在做的事。</p><span className="note-rule"/></section></aside>}</div>}
    <footer><span>知会 CLASSBOARD</span><span>班级里的重要消息，一起记得。</span><span>北京时间 · 已读仅保存在本机</span></footer>
    </main></div>
    {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
    {login&&<Login onClose={()=>setLogin(false)} onLogin={a=>{setAdmin(a);setLogin(false);setToast(`欢迎，${a.display_name}`);}}/>}
    {edit&&<Modal title={'id'in edit?'编辑通知':'发布班级通知'} onClose={()=>setEdit(null)}><NoticeForm initial={edit} onSave={save} onCancel={()=>setEdit(null)} label={'id'in edit?'保存修改':'发布通知'}/></Modal>}
    {detail&&<Modal title="通知详情" onClose={()=>setDetail(null)}><div className="detail-content"><div className="notice-meta"><span className={`category-badge ${catClass[detail.category]}`}>{detail.category}</span>{detail.pinned&&<span className="pin-label"><Pin size={13}/>置顶</span>}<span>{statusNames[detail.status]}</span></div><h2>{detail.title}</h2><p className="detail-byline">{detail.author_name} · {formatDate(detail.published_at||detail.created_at,true)}</p><div className="detail-body">{detail.body}</div><dl>{detail.event_at&&<><dt>活动时间</dt><dd>{formatDate(detail.event_at,true)}</dd></>}{detail.deadline_at&&<><dt>截止时间</dt><dd>{formatDate(detail.deadline_at,true)} · {countdown(detail.deadline_at,now)}</dd></>}{detail.location&&<><dt>地点</dt><dd>{detail.location}</dd></>}{detail.audience&&<><dt>通知对象</dt><dd>{detail.audience}</dd></>}</dl>{detail.source_text&&<details><summary>查看导入原文</summary><pre>{detail.source_text}</pre></details>}{detail.warnings?.length? <div className="warning">{detail.warnings.map(w=><p key={w}>{w}</p>)}</div>:null}<div className="modal-actions"><button className="button primary" onClick={()=>setDetail(null)}><Check size={17}/>我知道了</button></div></div></Modal>}
    {confirm&&<Modal title={confirm.action==='publish'?'确认审核发布':confirm.action==='reject'?'驳回这条草稿':'归档这条通知'} onClose={()=>setConfirm(null)}><div className="detail-content"><p>「{confirm.n.title}」</p><p className="muted">{confirm.action==='publish'?'请确认时间、地点与通知内容准确。发布后全班可见。':confirm.action==='reject'?'驳回后保留记录，不会对游客展示。':'归档后将从公开看板移除，记录仍保留在管理页。'}</p><div className="modal-actions"><button className="button secondary" onClick={()=>setConfirm(null)}>取消</button><button className="button primary" disabled={actionBusy} onClick={()=>void doAction()}>{actionBusy?'处理中…':'确认'}</button></div></div></Modal>}
  </div>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div><Inbox size={30}/></div><h3>{title}</h3><p>{text}</p></div>;}
function Login({onClose,onLogin}:{onClose:()=>void;onLogin:(a:Admin)=>void}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const data=new FormData(e.currentTarget);try{const result=await api<{admin:Admin}>('/login',{method:'POST',body:JSON.stringify(Object.fromEntries(data))});onLogin(result.admin);}catch(err){setError((err as Error).message);}finally{setBusy(false);}};
  return <Modal title="班委登录" onClose={onClose}><form className="notice-form" onSubmit={submit}><p className="muted">登录后可发布和管理班级通知。</p><label>账号<input name="username" required autoComplete="username" maxLength={64} placeholder="班委账号"/></label><label>密码<input name="password" type="password" required autoComplete="current-password" maxLength={256} placeholder="输入登录密码"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'正在登录…':'登录班委工作台'}<ArrowRight size={17}/></button><p className="field-hint">账号由网站维护者创建，暂不开放自行注册。</p></form></Modal>;
}
